baseurl = "https://www.thealphasguide.com/"
title = "Путеводитель aльфа-клонов по Новому Эдему"
languageCode = "ru"

theme = "hugo-theme-learn"
publishdir = "public"
builddrafts = true

[params]
  menu = [
    "start",
    "rookie-fitting",
    "market",
    "career-agents",
    "upgrading-ships",
    "new-goals",
    "training",
    "corps",
    "learn-more",
    "reference"
  ]
  editURL = "https://github.com/ka5huk3n/alpha-guide/edit/translated-ru/content/"
